### ISSUE TITLE
settle: Situation.OpenPRFound is always false in production

### ISSUE THREAD

**Issue by jordansmall** [jordansmall/spindrift#2553]
## Finding

`cmd/launcher/main.go`, recoverByNumber (around line 999-1047): the function enters its `if !res.Found { ... }` block only when `res.Found` is false, and inside that block (line ~1041) calls:

```go
sit := s.SituationFor(iss.number, res.Found, result)
```

Since this line only executes inside the `!res.Found` branch, `res.Found` is provably always `false` at this call site in production -- there is no code path where `SituationFor` is called here with a true value. `Situation.OpenPRFound` (cmd/launcher/internal/settle/situation.go) is consequently a constant `false` whenever this call site produces it, which means `SettleRelayedBranch`'s hard-precondition guard (`if sit.OpenPRFound { return false }`, cmd/launcher/internal/settle/adopt_relayed.go ~line 181) is dead code in production -- it can only ever be exercised by a test that constructs a Situation with OpenPRFound: true directly, never by a real recoverByNumber call.

This was introduced in commit 6d38b6bd ("fix(settle): thread real OpenPRFound through Situation"), whose message describes it as fixing a previously-hardcoded-false value by "threading the real fact" -- but the value threaded through is provably constant false at its one production call site, so the fix doesn't actually change runtime behavior; it only makes the always-false value explicit rather than literal.

## Analysis

This is not a functional bug (the guard, even though unreachable, produces the same correct behavior a hardcoded false always did), but it's worth a human decision on the design: either (a) this is intentional defensive programming / future-proofing for a caller that might someday pass true, and the OpenPRFound field, the exported SituationFor threading, and the hard-precondition guard should stay as-is with maybe a doc note clarifying it's currently always false in production, or (b) it's accidental complexity that should be simplified away (e.g. drop the field/guard until there's an actual caller that can supply true, or restructure recoverByNumber so the already-known "no open PR" fact doesn't need re-threading through a struct field that can never be anything else).

Found by review during #2501 (PR agent/issue-2501)

## Acceptance Criteria

- [ ] Decide whether the OpenPRFound field and its threading is intentional defensive programming or accidental complexity
- [ ] If intentional: add clarifying documentation that this value is always false in production and why
- [ ] If accidental: simplify by removing the field/guard or restructuring the call site accordingly
